name: "Bug Report"
about: "Report a reproducible bug in Mind Care. Provide steps, expected vs actual behavior, and environment details."
title: "Bug: "
labels: "bug"
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug — the clearer the report, the faster we can fix it. Please fill in the sections below.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: One-line summary of the bug
      placeholder: "e.g. music playback stops when switching tabs"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal, numbered steps to reproduce the issue
      placeholder: "1. Go to ...\n2. Click ...\n3. Observe ..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser/OS/version or app version (if known)
      placeholder: "e.g. Chrome 120 on Windows 11"

  - type: textarea
    id: logs
    attributes:
      label: Error messages or logs
      description: Paste console errors, stack traces, or relevant logs (optional)

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Anything else that might help reproduce or diagnose the issue (optional)
